Description: >
  Create a VPC with a single, public subnet and an Internet gateway. Included are a VPC endpoint to
  S3 and a private hosted zone.

Parameters:
  VpcCidr:
    Type: String
    Description: The VPC's network address in CIDR notation
    Default: 10.0.0.0/16
  SubnetCidr:
    Type: String
    Description: The public subnet's network address in CIDR notation
    Default: 10.0.16.0/20
  EnvName:
    Type: String
    Description: Resource name prefix representing the environment
    Default: Prod
  PrivateZoneApex:
    Type: String
    Description: The name of the private hosted zone to create
    Default: gavin-tech.com

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvName}-Vpc-Vpc
        - Key: EnvName
          Value: !Ref EnvName
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${EnvName}-Vpc-Igw
        - Key: EnvName
          Value: !Ref EnvName
  VpcGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref Vpc
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref SubnetCidr
      VpcId: !Ref Vpc
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvName}-Vpc-Sub
        - Key: EnvName
          Value: !Ref EnvName
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: !Sub ${EnvName}-Vpc-Tab
        - Key: EnvName
          Value: !Ref EnvName
  DefaultRoute:
    Type: AWS::EC2::Route
    DependsOn: VpcGatewayAttachment
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet
  PrivateHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref PrivateZoneApex
      VPCs:
        - VPCId: !Ref Vpc
          VPCRegion: !Ref AWS::Region
      HostedZoneTags:
        - Key: Name
          Value: !Sub ${EnvName}-Vpc-Tab
        - Key: EnvName
          Value: !Ref EnvName
  VpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref Vpc
      RouteTableIds: [!Ref RouteTable]
      ServiceName: !Join
        - "."
        - - com.amazonaws
          - !Ref AWS::Region
          - s3

Outputs:
  VpcId:
    Description: A reference to the created VPC
    Value: !Ref Vpc
    Export:
      Name: !Sub ${EnvName}-Vpc-Out-VpcId
  SubnetId:
    Description: A reference to the created subnet
    Value: !Ref Subnet
    Export:
      Name: !Sub ${EnvName}-Vpc-Out-SubnetId
  PrivateHostedZoneId:
    Description: A reference to the created private hosted zone
    Value: !Ref PrivateHostedZone
    Export:
      Name: !Sub ${EnvName}-Vpc-Out-PrivateHostedZoneId
